const express = require('express');
const fs = require('fs');
const { google } = require('googleapis');
const path = require('path');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 10000;

// Load OAuth2 client and token paths
const CREDENTIALS_PATH = '/etc/secrets/credentials.json';
const TOKEN_PATH = '/etc/secrets/token.json';
const SCOPES = ['https://www.googleapis.com/auth/youtube.force-ssl'];

function authorize() {
  const content = fs.readFileSync(CREDENTIALS_PATH);
  const credentials = JSON.parse(content);
  const { client_secret, client_id, redirect_uris } = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);

  const token = JSON.parse(fs.readFileSync(TOKEN_PATH));
  oAuth2Client.setCredentials(token);
  return oAuth2Client;
}

const youtube = google.youtube({ version: 'v3', auth: authorize() });

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

app.post('/generate', async (req, res) => {
  const { content, title, mode } = req.body;

  if (!content) return res.status(400).send('Missing content');

  const lines = content
    .split('\n')
    .map(line => line.replace(/^\d+\.|\d+\)|-/, '').trim())
    .filter(Boolean);

  const videoIds = [];
  for (const line of lines) {
    try {
      const response = await youtube.search.list({
        part: 'snippet',
        q: line,
        maxResults: 1,
        type: 'video',
      });

      const items = response.data.items;
      if (items.length > 0) {
        videoIds.push(items[0].id.videoId);
      }
    } catch (error) {
      console.error(`Search error for "${line}":`, error);
    }
  }

  if (videoIds.length === 0) return res.status(500).send('No videos found');

  try {
    const playlistResponse = await youtube.playlists.insert({
      part: 'snippet,status',
      requestBody: {
        snippet: {
          title: title || `SSGen Playlist ${new Date().toLocaleString()}`,
          description: 'Generated by SSGen: vibe-powered playlists by ShortStroke & Solace.'
        },
        status: {
          privacyStatus: 'private'
        }
      }
    });

    const playlistId = playlistResponse.data.id;

    for (const videoId of videoIds) {
      await youtube.playlistItems.insert({
        part: 'snippet',
        requestBody: {
          snippet: {
            playlistId: playlistId,
            resourceId: {
              kind: 'youtube#video',
              videoId: videoId
            }
          }
        }
      });
    }

    const playlistURL = `https://www.youtube.com/playlist?list=${playlistId}`;
    res.json({ playlistURL });
  } catch (err) {
    console.error('YouTube playlist creation failed:', err);
    res.status(500).send('Failed to create playlist');
  }
});

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`🟢 SSGen server running at http://localhost:${PORT}`);
});